#!/bin/bash
#
# Enhace the git-rebase(1) todo file with additional information about each
# commit, such as the author date, the author name and e-mail, as well as the
# commit message. The user then has the chance to edit any of this information
# when 'GIT_SEQUENCE_EDITOR' is invoked on the decorated git-rebase(1) todo
# file. Upon successful execution of 'GIT_SEQUENCE_EDITOR', parse the user's
# changes and prepare a 'git commit --amend' 'exec' step to be called after each
# 'pick'ed commit.

fiddle_todo="$1".fiddle

trap '{
	exit_code=$?
	rm -f "$fiddle_todo" || :
	exit $exit_code
}' EXIT

FIDDLE_MESSAGE="$(cat <<-'EOF'
	#
	# WARNING: any changes to the author, date and message are only retained
	#          for 'picked' commits.
EOF
)"

function trim () {
	echo "$1" | sed -e '
		s/^[[:space:]]*//
		s/[[:space:]]*$//
	'
}

function create_git_pretty_format () {
	local format=

	# --[no-]fiddle-author
	if ! [ "$GIT_FIDDLE_AUTHOR" = false ]; then
		format="$(trim "$format %an")"
	fi

	# --[no-]fiddle-date
	if ! [ "$GIT_FIDDLE_DATE" = false ]; then
		local x=
		if [ ! -z "$format" ]; then x="$x("; fi
		x="${x}%ad"
		if [ ! -z "$format" ]; then x="$x)"; fi
		format="$(trim "$format $x")"
	fi

	# --[no-]fiddle-subject
	if ! [ "$GIT_FIDDLE_SUBJECT" = false ]; then
		format="$(trim "$format> %s")"
	fi

	# --[no-]fiddle-body
	if ! [ "$GIT_FIDDLE_BODY" = false ]; then
		format="$(trim "$format"$'\n%b')"
	fi

	echo "$format"
}

GIT_PRETTY_FORMAT="--format=$(create_git_pretty_format)"

function prepare () {
	while read -r line; do
		if [ -z "$line" ] || [[ $line =~ ^[[:space:]]?# ]]; then
			printf "%s\n" "$line"
		else
			read -r action sha rest < <(echo "$line")
			printf "%s %s %s\n" "$action" "$sha" \
				"$(git --no-pager show -s "$sha" "$GIT_PRETTY_FORMAT" | \
					git stripspace)"
		fi
	done < "$1" > "$2"
	echo "$FIDDLE_MESSAGE" >> "$2"
}

function fiddle_sequence_editor () {
	if [ -z "$GIT_FIDDLE_SEQUENCE_EDITOR" ]; then
		GIT_FIDDLE_SEQUENCE_EDITOR="$(git config sequence.editor)"
		if [ -z "$GIT_FIDDLE_SEQUENCE_EDITOR" ]; then
			GIT_FIDDLE_SEQUENCE_EDITOR="$(git var GIT_EDITOR)" || return $?
		fi
	fi
	eval "$GIT_FIDDLE_SEQUENCE_EDITOR" '"$@"'
}

function esc () {
	echo "$1" | sed -e "s/'/'\"'\"'/g"
}

function emit () {
	local -r author="$1"
	local -r date="$2"
	local -r message="$3"

	local c=
	[ ! -z "$date" ] && c="GIT_AUTHOR_DATE='$date'"
	c="$c git commit --amend --no-edit"
	[ ! -z "$date" ] && c="$c --date='$(esc "$date")'"
	[ ! -z "$author" ] && c="$c --author='$(esc "$author")'"
	[ ! -z "$message" ] && c="$c --message=\$'$(esc "$message")'"

	echo "exec bash -c \"$(echo "$c" | sed \
		-e 's/\\/\\\\/g' \
		-e 's/"/\\"/g'
	)\""
}

function apply () {
	set -eo pipefail

	local scanning_body=false
	local mod_message=
	local mod_subject=
	declare -a mod_date mod_author

	while read -r line; do
		read -r action sha rest < <(echo "$line")
		if echo "$action" \
			| grep -E -q '^(pick|p|drop|d|reword|r|edit|e|squash|s|fixup|f)$'
		then
			if [[ "$sha" =~ ^[0-9a-z]{6,}$ ]]; then

				# flush the current scan
				if $scanning_body; then
					emit "${mod_author[*]}" "${mod_date[*]}" "$mod_message"
				fi

				# retain the action
				echo "$action $sha"

				# reset state
				scanning_body=false
				mod_message=
				mod_subject=
				unset mod_date mod_author
				declare -a mod_date mod_author

				# begin a fresh scan for 'pick' actions
				if [[ "$action" == pick ]]; then
					# parse author
					# take until '(' if date is present
					# or   until '>' if subject is present
					# or   until EOL otherwise

					# parse timestamp
					# (optional) parse '('
					# take until '(' if has parsed ')'

					# parse subject line
					# parse '>'
					# take until EOL



					# m=0
					# for col in $rest; do
					# 	if [[ "$col" == by: ]]; then m=1; else
					# 		case $m in
					# 			0) mod_date+=("$col"); ;;
					# 			1) mod_author+=("$col"); ;;
					# 		esac
					# 	fi
					# done
					scanning_body=true
					continue
				fi
			fi
		fi

		if $scanning_body; then
			mod_message="$mod_message\n$line"
		fi
	done < <(git stripspace --strip-comments < "$1")

	# flush the current scan
	if $scanning; then
		emit "${mod_author[*]}" "${mod_date[*]}" "$mod_message"
	fi
}

# kick off
prepare "$1" "$fiddle_todo" && \
	fiddle_sequence_editor "$fiddle_todo" && \
		apply "$fiddle_todo" > "$1" || exit $?;
